### ISSUE TITLE
Using with Android Browser 4.2.2 ?

### ISSUE THREAD

**Issue by sunni2002** [tkem/mopidy-http-kuechenradio#19]
Hi tkem,

I wanted to use this special client on my Android 4.2.2. Tablet. I can open the client with the android browser but i can't control anything. After some research in the www i found out that there are websockets necessary but the android browser doesn't have.
http://caniuse.com/#search=websocket
Is there any way to use this client with this browser?

**Comment by tkem** [comment]
Sorry, the Mopidy JS library which is used by this client uses Websockets, and there's currently no alternative that I'm aware of. So apparently no luck with Android <4.4.

Thanks for posting, anyway, since I was not aware that Android only supports Web sockets since 4.4; I though any 4.x version could use that...

**Comment by jodal** [comment]
For Android <4.4, you can still use [Chrome Browser from Google Play](https://play.google.com/store/apps/details?id=com.android.chrome). This became the default browser as of Android 4.4, IIRC.

As for WebSockets support in general, see http://caniuse.com/#feat=websockets.

**Comment by sunni2002** [comment]
Thanks fpr your fast response.
Yes, with Chrome Browser everything works great. My problem is, that i 
wants to represent this client in a webview. I can use webviews in my 
home automation app ... but webviews needs websockets. And my tablet 
doesn't get any update to 4.4 :-(
Are there any other options for me?


Am 08.01.2015 um 01:26 schrieb Stein Magnus Jodal:

**Comment by tkem** [comment]
Before spending too much time on this, I should tell you that mopidy-http-kuechenradio will no longer be developed (I should update the README on this). I'm working on a new mobile Web client/hybrid app, tkem/mopidy-mobile, but it will take some time before that becomes functional.

Sorry for the inconvenience.

**Comment by jodal** [comment]
@sunni2002 If you're up to developing something yourself, we have a HTTP POST API available which will be usable in the old Android Browser, ref. https://docs.mopidy.com/en/latest/api/http/#http-post-api. This will give you access to all the same commands as the WebSocket API, but you will not get any events from Mopidy.

**Comment by tkem** [comment]
Thinking about it, it might be really nice if Mopidy.js provided some fallback-mechanism using the POST API if WebSockets are not available. I guess most "active" requests could be implemented using AJAX as well, without any changes in client code. As for event handling, it might be possible to "fake" this using polling; i.e. send an AJAX request every <configurable> seconds checking for playback/tracklist/playlists/whatever changes, and emit the corresponding events on the client. Would result in a (probably significant) delay on the client side, and might require some server-side support, of course...

**Comment by jodal** [comment]
It's clearly possible, but I think its the wrong place to spend any effort, given that WebSockets is supported quite widely now. Android Browser is something like 1% of the browser market.

**Comment by tkem** [comment]
Well, I didn't mean you (or me, for that matter) to start working on that, but if someone who *really* wants that feature posts a PR, I gues it would be welcome?

**Comment by tkem** [comment]
Closing this, since Mopidy-HTTP-Kuechenradio will no longer be maintained.
